# Personalize your website info here
title:            Bryan D. Loy, Ph.D.
tagline:          'All things fatigue in medicine and exercise'
description:      'Website and Blog for Bryan Loy'
url:              http://BryanLoy.github.io
author:
  name:           'Bryan Loy'
  url:            https://twitter.com/BryanLoy1

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
